name: Build and test wheels

on:
  push:
    branches:
      - main
      - test-publish
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build-distribution-artifacts:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          version: "0.8.15"

      - name: Build artifacts
        # working-directory: ${{ inputs.pyproject-directory }}
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          path: dist

  publish:
    runs-on: ubuntu-24.04
    environment: release
    needs: [ 'build-distribution-artifacts' ]
    permissions:
      id-token: write
    steps:
      - name: Download all
        uses: actions/download-artifact@v4.2.0
      - name: Move to dist
        run: |
          mkdir dist
          cp */*.{whl,gz} dist/.
      - name: Publish distribution to Test PyPI
        if: github.event_name == 'push' && github.branch_name == 'test-publish'
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution to PRODUCTION PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@v1.13.0
